### ISSUE TITLE
new tweens in for loop

### ISSUE THREAD

**Issue by kuyucakli** [tweenjs/tween.js#124]
Hi,
I have just installed your library and trying to use it with paper.js. I am trying to animate the segments of the path... Code is as below:

for (var i = 0; i < this.numSegment; i ++){
                    var tween = new TWEEN.Tween( { x: segments[i].point.x , y: segments[i].point.y } )
                    .to( { x: this.pivot.x , y:this.pivot.y }, 2000 )
                    .easing( TWEEN.Easing.Circular.InOut )
                    .onUpdate( function () {
                        segments[i].point.x = this.x;
                        segments[i].point.y = this.y;
                    } );
                     tween.delay(Math.ceil(Math.random() \* 300));
                     tween.start();
                }

But only one of the segments moves... ?

**Comment by benjyu** [comment]
Here is your code:

```
for (var i = 0; i < this.numSegment; i ++){
    var tween = new TWEEN.Tween( { x: segments[i].point.x , y: segments[i].point.y } )
        .to( { x: this.pivot.x , y:this.pivot.y }, 2000 )
        .easing( TWEEN.Easing.Circular.InOut )
        .onUpdate( function () {
            segments[i].point.x = this.x;
            segments[i].point.y = this.y;
        } );
    tween.delay(Math.ceil(Math.random() * 300));
    tween.start();
}
```

The for loop enters a new loop every time your `tween.start()` fires. But the `tween.onUpdate()` function is not necessarily fired at that moment, because `tween.onUpdate()` is an event listener that listens to every _update_ event. So when `var i` finished `0` and entered `1`, the `tween.onUpdate()` might not have been fired yet. When the loop finished iteration, `var i` is now 2, and `tween.onUpdate()` only fires on the last index of your `segment` array. That's why the only one that moves is `segment[2]`.

I think this has to do with _closures_. According to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures):

> A closure is the combination of a function and the lexical environment within which that function was declared. This environment consists of any local variables that were in-scope at the time the closure was created.

So because your for loop does not have closure for each iteration, the functions within each iteration reference to `var i` in the larger context of the for loop, but not within themselves. If you add an [Immediately-Invoked Function Expression](https://developer.mozilla.org/en-US/docs/Glossary/IIFE) then each iteration will have a memory of `var i` themselves, so that they will respect the iteration. In short, your code now looks like this:

```
for (var i = 0; i < this.numSegment; i ++){
    (function(index){ // this is the IIFE
            var tween = new TWEEN.Tween( { x: segments[i].point.x , y: segments[i].point.y } )
            .to( { x: this.pivot.x , y:this.pivot.y }, 2000 )
            .easing( TWEEN.Easing.Circular.InOut )
            .onUpdate( function () {
                segments[i].point.x = this.x;
                segments[i].point.y = this.y;
            } );
        tween.delay(Math.ceil(Math.random() * 300));
        tween.start();
    })(i);
}
```

Or, you could simply use the `Array.prototype.forEach` method to iterate through your `segments` array, because this method will effectively create closures for each iteration, like so:

```
segments.forEach(function(segment){
        var tween = new TWEEN.Tween( { x: segment.point.x , y: segment.point.y } )
            .to( { x: this.pivot.x , y:this.pivot.y }, 2000 )
            .easing( TWEEN.Easing.Circular.InOut )
            .onUpdate( function () {
                segment.point.x = this.x;
                segment.point.y = this.y;
            } );
        tween.delay(Math.ceil(Math.random() * 300));
        tween.start();
})
```

Hope this helps :) I encountered a similar problem and did some research on this.
