### ISSUE TITLE
ES6

### ISSUE THREAD

**Issue by mixonic** [tweenjs/tween.js#155]
Howdy!

I'd like to use Tween.js in a project, one that will be written in ES6.

Is there any interest in porting Tween.js to ES6? I am happy to undertake this. And happy to answer any questions.

**Comment by superlukas** [comment]
I'm using tween.js with webpack and [6to5](https://6to5.org) without any problems. I'm afraid porting tween.js to ES6 and then transpiling it to ES5 would hurt performance more than anything else.

**Comment by mixonic** [comment]
@superlukas A library being written in ES6 does not mean it must be published as ES6.

Ember.js has been written with ES6 module support for nearly a year now. We still only export the library as a ES3-safe build. Some dependencies, like HTMLBars, are published as ES6, transpiled CJS, and transpiled AMD. This give us great flexibility.

**Comment by superlukas** [comment]
@mixonic I still don't get why you'd need the library to be written in ES6. Native ES6 modules are nice, but tween.js supports CommonJS already which all tranpilers support anyway. I send in a PR yesterday that adds full UMD support.

As I said, I use tween.js with ES6 myself, but I still don't see any reason for the library to be written in ES6. Transpiling, as far as I'm concerned, adds a potential overhead without anybody gaining anything from it. Do you mind telling me what your exact use case is? Do you want to use the new `System` module system or something?

**Comment by sole** [comment]
Hi friends

I just found yesterday that I hadn't got any notification for issues in tween for the last two or three months, and I'm so sorry about that. I don't remember unsubscribing from this, but ugh.

I have been thinking about an ES6 version too--mostly because of the module system. Thanks for bringing this up! :+1: 

I also have been thinking about going *megamicromodular* and split every easing function onto its own module, move tween core to its own module, etc. Publishing the stuff to npm and then assembling the whole thing together in a "full" package. But you could use the functions individually too-maybe you're just interested in them!

But I don't want to be the bottleneck in tween.js so I'm working on moving it to a more community-based project. Therefore I created a project under the tweenjs organisation: https://github.com/tweenjs/es6-tween

I believe the best option here is to be "disruptive" and write this new version from the ground up. With proper version number, transpiler to publish to npm, etc.

I've taken added a number of "desired" features to the issues, please feel free to join in the discussion and let's see if we can shape this together. I guess a good place to start is by answering the first issue: [what's the point?](https://github.com/tweenjs/es6-tween/issues/1)

**Comment by mixonic** [comment]
@sole consuming the internals is exactly what I originally had in mind.

In Ember libraries, we often import a dependency as ES6 and build it into our own codebase. A good example is HTMLBars, which is published to npm containing three versions of the code.

* A ES2015 (yes, they renamed it ES2015) module version at  `/es6/`: https://github.com/tildeio/htmlbars/blob/master/Brocfile.js#L121
* An AMD version built concatenated into a single file in `/amd/`: https://github.com/tildeio/htmlbars/blob/master/Brocfile.js#L129
* A CJS version at `/cjs/`: https://github.com/tildeio/htmlbars/blob/master/Brocfile.js#L136

These are then consumed in three ways:

* The ES6 version is consumed by other ES6 libraries, most notably Ember itself. In these cases, the consuming library is basically performing a static dependency compilation- packaging the code into its own releases.
* The AMD version is used for HTMLBars stand-alone in the browser.
* The CJS version is used by node libraries.

Even if you choose to use ES2015 in your app codebase, I recommend you only put ES6 modules in the built dist files. Many libraries only use a module transpiler, and as full ES6 feature transpilation is a bit more expensive and quirky requiring that a 3rd party build your ES6 code with any one of the options is risky. Sticking to ES6 exports that only contain module syntax provides the portability benefits without any other requirements on the consumer's build pipeline.

**Comment by superlukas** [comment]
Here's what I would do:

* One ES6 module (both ES6 code and ES6 modules)
* One ES5 module (transpiled to ES5 code with UMD modules and global variables as a fallback)

It's the simplest/most obvious solution and it should work for everybody, including Three.js users who want (?) global variables, Browserify/Requirejs users (most people today), users like us using ES6 transpilers and users in the future who just want ES6 all the way.

**Comment by thejameskyle** [comment]
You guys might want to check out https://github.com/6to5/6to5-library-boilerplate

**Comment by sole** [comment]
Thanks all for the input. I'm trying to clean down this repository's issues so please continue the discussion over at the "potentially new and shiny repo" here: https://github.com/tweenjs/es6-tween/issues/1
