### ISSUE TITLE
NaN if duration argument not supplied

### ISSUE THREAD

**Issue by pehrlich** [tweenjs/tween.js#180]
This doesn't work:

```javascript
  new TWEEN.Tween( ring.material ).to( { opacity: 1 } ).start();
```

This does:

```javascript
  new TWEEN.Tween( ring.material ).to( { opacity: 1 }, 400 ).start();
```

In a land of default conventions, the former is not a bad syntax.  In a land of wild and fantastic WebGL, NaNs can take a long time to find.

I propose either
 - Throw an error
 - Give a default

When the second, duration, argument is not supplied.

**Comment by sole** [comment]
May I ask you for a test case? There is a default `_duration` indeed: https://github.com/tweenjs/tween.js/blob/master/src/Tween.js#L119-L123

Perhaps you're passing in something else other than `undefined`-that's why I'm asking for a test case.

**Comment by pehrlich** [comment]
Interesting.  Unfortunately, the code I was working on at the time is long-forgotten.  Will update if I ever encounter again~

**Comment by sole** [comment]
No worries! Thanks :)

**Comment by wilson0x4d** [comment]
@sole it would be nice if there were a type check for the second parameter, due to some bad sample code on the net i made the mistake of providing an easing function.

ie. changing this:
```javascript
		if (duration !== undefined) {
			this._duration = duration;
		}
```
to this:
```javascript
		if (typeof(duration) === 'number') {
			this._duration = duration;
		}
```

i would personally opt for an error here, but i can see that most of this code does not emit errors/logs, so the above is in the spirit of "it just works anyway" when someone does something they shouldn't have (or when the parameter is omitted.)

being rigid has the value of not misleading users when they've made a mistake, so personally I would personally opt for something like this:

```javascript
		if (typeof(duration) === 'number') {
			this._duration = duration;
		} else if (typeof(duration) !== 'undefined') {
			throw 'Invalid parameter specified in `Tween.to`, expected `duration` (number)';
		}
```

Thanks!
