### ISSUE TITLE
[ Question ] keeping the same speed when tweening random distances.

### ISSUE THREAD

**Issue by schoening** [tweenjs/tween.js#189]
I am trying to tween a sprite across the screen targeting randomly selected nodes.
The nodes are spread around unevenly and the problem is that I can't figure out how to set the speed of the tween so that it the movement will be constant regardless of the distance between two nodes.

My example: 
https://dl.dropboxusercontent.com/u/53738503/polar%20rescue/0.1/index.html

The polar bear should move at constant velocity. Instead it obviously depending on the distance between two nodes.

     var tween = new TWEEN.Tween( current_position )
          .to( target_position, 5000  ) // The timer will have to be set based on the distance between two Nodes.
          .onUpdate(function(){
            sprite.position.x = this.x;
            sprite.position.y = this.y;
          })
          .onComplete( tweenComplete )

I tried fixing this by setting the speed like this:
    var a = current_node, var b = target_node;
    var distance = Math.sqrt( (a.x - b.x) * (a.x - b.x) + ( a.y - b.y ) * ( a.y - b.y ) );

After that failed I tried:

    var scalar = 50;
    var velocity = 5;
    var time = distance * scalar / velocity;´
But again with no avail.

Help please... Right now the game is just using a constant speed value. The code is very messy. Just tell me what you need to know :)

**Comment by sole** [comment]
So I think the first step will be to actually explain what you want to do in more accurate terms :-)

> I can't figure out how to set the speed of the tween so that it the movement will be constant regardless of the distance between two nodes

* there is no "speed" in the tween, there is initial and final points (from which you can deduct a distance) and there is also the time to cover said distance i.e. the `duration` parameter for the tween
* and what do you mean with a "constant movement"? I believe you mean *constant speed* i.e. no matter how far the points are the bear always moves at the same speed between them

There is no built-in support in this library to do what you want but I'm going to suggest what came to my mind in the first place--maybe it will help you:

If I understood what you mean correctly, you should set a constant speed you want the bear to walk at first. I guess that's the `velocity = 5` you used.

Once you have that speed, the time to cover the distance should be different per tween.

Physics 101: `distance = speed * time` (assuming constant speed and no acceleration :wink:)

Since you know `distance` and `speed`, shuffle things around in the equation: `time = distance / speed`

And create each tween calculating the time individually per tween.

But that's what you were doing? except for the scalar part.

I would suggest if the code is very messy that you build a smaller test case and try to focus just on this issue. I'm not going to look at your game code, sorry :)

**Comment by schoening** [comment]
Thanks for the answer.

Oh No! I never expected you to go through that mess :) Sorry if you felt that was implied :p 

Thanks for the answer tho!
