### ISSUE TITLE
[ECO MODE] Tween.js Eco Mode

### ISSUE THREAD

**Issue by dalisoft** [tweenjs/tween.js#195]
Hi @tweenjs authors!
I think the Eco (Economy, Battery life) mode. requestAnimationFrame need be stopped after all tweens completed for Eco-Mode;
But i have no idea how to implement it.

**Comment by sole** [comment]
So there are two things we could do as tween.js authors (this is you too, @dalisoft :wink:)

* Nothing. Leave it up to the code that is *calling* `TWEEN.update()` to decide whether it should call it again, maybe querying if there are active tweens. Problem with this is: you might end up creating an active tween afterwards and it won't be run because nothing is calling `TWEEN.update()` regularly.
* Maybe emit an event when all tweens are completed, and another one when a tween is added or needs updating (but only if coming from an 'idle' state). Right now, we are not emitting any sort of events, it's all about polling / callbacks and asking `TWEEN` for number of tweens etc.

I think this should go to "v2". I'd prefer not to add any of this to the current version.

**Comment by dalisoft** [comment]
Thanks @sole.
I am working in Eco-Mode

**Comment by dalisoft** [comment]
Eco decreases performance, but can save up to 50% battery life. Eco mode i maked with own idea and under testing.

**Comment by trusktr** [comment]
In my case, I solved this problem by not using `TWEEN.update()`, and using `tween.update()` on a per-instance basis. So, for example, if you are making your own animation loop with `requestAnimationFrame`, it would be like this:

```js

let obj = /* ... some object to animate ... */
let tween = new TWEEN.Tween(obj)
    .to({someValue: 100}, 5000)
    .onComplete(() => tween.running = false)
    .onStop(() => tween.running = false)

requestAnimationFrame(function loop(time) {
    
    if (!tween.running) {
        tween.running = true
        tween.start()
    }

    tween.update(time)

    if (tween.running) requestAnimationFrame(loop)
})
```

**Comment by dalisoft** [comment]
@trusktr 
I sure, your way isn't better than `TWEEN.update`. Because, one `requestAnimationFrame` with inside multiple callback calls IS BETTER THAN `requestAnimationFrame` on each callback call. This reduced performance too.

**Comment by mikebolt** [comment]
@dalisoft is correct. I ran an experiment to compare the performance of
using many RAF callbacks versus using one RAF callback which updates
everything, and using a single callback was slightly better.

The best way to save battery is to lower the framerate. If you only call
update every 5 times the RAF callback is run, that's 12 fps, which is the
same as standard definition TV.

**Comment by trusktr** [comment]
Yes, of course, having more function calls i always more expensive than having only one function call, but in a complex modular application this will likely be inevitable (multiple functions).

In my 3D library (no official docs or demos yet, but see http://mightydevs.com for a tiny demo), "render tasks" are functions that are added or removed in order to animate components, and it is impossible to do it all with a single render task (render tasks are a layer on top of requestAnimationFrame, and behind the scene there is only one single requestAnimationFrame function which loops through an array to fire all render tasks). When a project gets big, it will be inevitable that developers will need to hook into the render loop in order to execute some module-specific render logic, and that inevitably means having multiple functions coming from various modules.
