### ISSUE TITLE
Desynchronization

### ISSUE THREAD

**Issue by Astrak** [tweenjs/tween.js#201]
Hello, 

it has been a few days now i am wondering how to solve a synchronization issue : i have many looped tweens in threejs that are working great.. unless i leave the tab and go back to it, or pause the animation (both `renderer.render(..)` & `TWEEN.update()`) : then all tweens get desynchronized. I think it is the same issue posted [there]( http://stackoverflow.com/questions/16101225/animation-synchronisation-in-three-js-with-tween-js) 2 years ago on stackoverflow. Someone noticed it 4 days ago and commented he will sort of notice you but i dont see the issue so here it is.

Also i wanted to know if it could come from the use of the computer's time with `Date.now()` so i tried to pass a time argument to the update function, (for example t, and t++ in the animation loop). I get an ugly result : my cpu shows a normal activity but tweens are hugely accelerated, regardless the increase of t each loop, before the FPS suddenly drop and the rendering stops.

im on windows7/intelHD graphics family/happens in all browsers

Thanks for your job, Tween & Three really are 2 wonderful libraries

**Comment by bchevalier** [comment]
I think that what you get is the following issue:
You change tab at time ```t```, when you go back, to your tab that is playing tweens, at time ```t + d``` the tweens all jump by a duration of ```d```. Therefore you see a huge acceleration. Since there are some tween synchronisation issues in Tweenjs, they are being emphasized by the phenomenon.

It is obviously an issue in Tweenjs and the best way to fix it might be to check for tab change using the visibility API of the browser and virtually pause de tweens so that when you go back to your tab, you go back at time ```t``` and not ```t + d```.

Following code could be used to handle the lost of focus of the page:
```
	if (typeof document.hidden === 'undefined') {
		console.warn('Cannot pause on lost focus because the browser does not support the Page Visibility API');
	} else {
		// Handle page visibility change
		// A clock offset starts being computed when the focus is lost
		// Starting time of the tweener is offset when the focus is back on the page
		// As if no time had passed
		var clockOffset;
		document.addEventListener('visibilitychange', function () {
			if (document.hidden) {
				// document became hidden
				clockOffset = clock.now();
			}

			if (!document.hidden) {
				// document is back (we missed you buddy)
				var elapsed = clock.now() - clockOffset;
				tween._startTime += elapsed;
			}
		}, false);
	}
```

**Comment by sole** [comment]
Yes, I think @bchevalier is right. Tween will just interpolate between values... if you step away from a tab the browser throttles things to be more efficient, and so you get less updates. When you come back it updates to a new value and you're seeing that sudden acceleration change (I guess, because I don't know what your code does).

This should be fixed externally to tween, so I'm tentatively closing this to see if I can empty the list a bit :P
