### ISSUE TITLE
Tween only work for one time and then break

### ISSUE THREAD

**Issue by shadeed** [tweenjs/tween.js#213]
Hello,

Thanks for the library.

In [this](http://codepen.io/shadeed/pen/e81f9994bf1aa94748610578ff8677e8) demo I want the line to play tween and tween2 infinitely, but after it's run for the first time the tween2 breaks and start working without tweening between the specified values for y.

Am I missing something? I want to chain between the tweens and it doesn't work.

Thanks,

**Comment by mikebolt** [comment]
It took me a while to figure this out. It looks like tween.js doesn't reset any values on the tween's object when it is started, even if it is being started for a second time. Here's what's happening now:

tween starts and tweens y from 200 to 240 linearly
tween2 starts and tweens y2 from 240 to 170 linearly
tween starts and tweens y *from 240* to 240, because it is still 240 from the end of the last time it tweened
tween2 starts and tweens y2 *from 170* to 170, because it is still 170
tween starts and tweens y from 240 to 240 again...
etc.

And that's why you get that on/off motion after the first run.

One solution is to follow example 11 and reset the values appropriately in the onComplete callback. Here's the code fixed using that method: http://codepen.io/anon/pen/EjBMBv . It didn't look right during the first run so I had it start on tween instead of tween2.

Here's a better solution: http://codepen.io/anon/pen/BNgbMe . This one tweens a single object rather than using two different objects. The advantage here is that the tween always starts wherever the last tween ended, so there are no jump discontinuities.

I hope this helps, and let me know if you need any clarification. I don't think this is a bug, but then again I'm not sure how tweens are supposed to behave when they are started a more than once.

**Comment by sole** [comment]
Yeah values are not reset to the original value. If you want them to start at a given value, you should use the `onStart` callback.

Thanks for the help @mikebolt :)
