### ISSUE TITLE
update bower registry to point to new repo url

### ISSUE THREAD

**Issue by sole** [tweenjs/tween.js#226]
It was discussed in #205 that the registry is pointing to the old repository.

The new one is `tweenjs/tween.js` and not `sole/tween.js`, but I have no idea of how to do such an update by reading the instructions in https://github.com/bower/registry

Furthermore, I didn't register the package in bower originally, so I'm at a complete loss here. If you know how to do this and want to do it, please go ahead and get that url updated. I'll thank you forever!

**Comment by SantanMaddi** [comment]
@sole this issue is very similar to [#134](https://github.com/bower/registry/issues/134). A bower package has already been created for the repo under your name. As tweenjs is now moved to a new repo, the solution proposed in the issue [#134](https://github.com/bower/registry/issues/134) is unregister the original bower package which points to the repo under your name and register the new version to the same name. Else, create a new package with a new name is an alternative (which I think is not the best solution).

**Comment by sole** [comment]
Someone needs to help do that. I don't use bower, and I don't intend to learn to use bower. So if someone in the community who uses bower and uses tween.js wants to help, this will be solved. Until then, it'll remain open :-/

**Comment by sole** [comment]
Apparently it has been updated and no one let us know. AHHH I LOVE OPEN SOURCE 🔪

**Comment by phazei** [comment]
It stopped redirecting and is looking for sole/tween.js again.
We've been using tween.js in our dependencies as `"tween.js": "@tweenjs/tween.js#^16.6.0"` for years, but it just stopped yesterday.  Said `bower tween.js#^16.6.0       ENOTFOUND Package @tweenjs/tweenjs not found`


Tried removing and adding fresh and got:
```
$ bower install tweenjs --save
bower tweenjs#*                 cached https://github.com/sole/tween.js.git#16.6.0
bower tweenjs#*               validate 16.6.0 against https://github.com/sole/tween.js.git#*
bower tween.js#^16.6.0       ENOTFOUND Package @tweenjs/tween.js not found
```

**Comment by mikebolt** [comment]
Please contact npm support. I don’t think I can help.
