### ISSUE TITLE
What does the variable "k" stand for?

### ISSUE THREAD

**Issue by richard-livingston** [tweenjs/tween.js#233]
Perhaps you could answer this question on StackOverflow: http://stackoverflow.com/questions/33529771/what-does-the-variable-k-stand-for

Just curious :)

**Comment by sole** [comment]
The formulas were initially [way more complex](https://github.com/tweenjs/tween.js/blob/4d1a4d2027ff08e7289a56778e6252a1e20d70c7/src/Tween.js#L136) and then Phillipe Elsass sent a patch that [simplified them](https://github.com/tweenjs/tween.js/blob/2dbeac6d65e0ac220bd56fa2b8922ab212cc3480/src/Tween.js#L220) and made everything more performant.

As to what does `k` stand for - well, I can't really answer because I didn't do those changes, but I can guess. It could have been `x`, or `y`, or `z`, but I guess those have 'dimensional' connotations of length, and likewise `i` or `j` are very much used in loops. So `k` is a good name for a parameter that doesn't mean anything in particular. This is my guess, but if you're really really curious, only @elsassph can answer. His commit is not in the list of commits because we were really bad at git back then and merged things manually and artisanally, but he's the author of the simplified formulas if I remember correctly.

Side note: wow, people are getting really creative at Stack Overflow.

**Comment by elsassph** [comment]
Ha ha I don't know why I chose `k`, and in fact I didn't remember that I contributed to this code - I've written these simplified equations for my old ActionScript tweening engine.

**Comment by richard-livingston** [comment]
@sole @elsassph Thanks for the details, was just curious.
