### ISSUE TITLE
String target values without plus sign prefix still treated as relative values.

### ISSUE THREAD

**Issue by mikebolt** [tweenjs/tween.js#239]
The title says it all. The fix for this should be easy, but I want to confirm that this is not the intended behavior.

**Comment by sole** [comment]
Oh, that sounds like a bug. It's not the intended behaviour... even though it's what's happening because the code just checks for the value being a String: https://github.com/tweenjs/tween.js/blob/e19a4c929bace618cd4a8ab1f36357f97a2353ae/src/Tween.js#L306-L308

It should check if there's a + or -, yes...

**Comment by sole** [comment]
Also as it turns out there are not tests for relative values, sigh...
