### ISSUE TITLE
can't use it in node.js

### ISSUE THREAD

**Issue by rosancoderian** [tweenjs/tween.js#252]
can i actually use this library in node.js?

/mnt/sda6/skripsi/multiplayer/node_modules/tween.js/src/Tween.js:13
    if ('performance' in window === false) {
                         ^

ReferenceError: window is not defined
    at /mnt/sda6/skripsi/multiplayer/node_modules/tween.js/src/Tween.js:13:23
    at Object.<anonymous> (/mnt/sda6/skripsi/multiplayer/node_modules/tween.js/src/Tween.js:31:3)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/mnt/sda6/skripsi/multiplayer/app.js:7:13)
    at Module._compile (module.js:413:34)

**Comment by 0x860111** [comment]
Guess not. It only client library, i cant imagine a case when you need animate something on the server.

**Comment by rosancoderian** [comment]
it's useful for making multiplayer game server, but i found an alternative and it's based on tween.js https://github.com/unstoppablecarl/Tweeno

**Comment by limikael** [comment]
It is also useful to run it under node.js if you want to create unit tests. Just saying...

**Comment by sandromartis** [comment]
I just ran into the exact same issue when I was trying to unit test my project under node.js (mocha).
I'm not familiar with the Tween.js codebase, but would it be possible to remove the dependency on `window`?
What is performance used for?

**Comment by mikebolt** [comment]
window.performance is used for the high performance "now" function:
https://developer.mozilla.org/en-US/docs/Web/API/Performance . The idea is
just that we want the best version of the "now" function. If there's no
"window" object then it can default to Date.now, or whatever node has. We
can save the "now" function on TWEEN instead of window.performance.

Also, we can probably improve performance slightly by removing the offset
subtraction from the fallback "now" function. The offset really doesn't
matter in this library.
On Jul 6, 2016 12:23 AM, "Sandro Martis" <notifications@github.com> wrote:

I just ran into the exact same issue when I was trying to unit test my
project under node.js (mocha).
I'm not familiar with the Tween.js codebase, but would it be possible to
remove the dependency on window?
What is performance used for?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tweenjs/tween.js/issues/252#issuecomment-230697552>,
or mute
the thread
<https://github.com/notifications/unsubscribe/ACCav1eyj7lXbkxwA5328LB4qC7hc_C8ks5qS1fRgaJpZM4H2lKP>
.

**Comment by mikebolt** [comment]
It turns out that `performance.now` isn't used because the function itself is faster (it may or may not be), but actually because it is supposed to return a 5 microsecond accurate timestamp, instead of just a 1 millisecond accurate timestamp. `Date.now` is supposed to work in node.js because it's part of JavaScript, not any browser API. To get a more accurate timestamp in node.js we can use `process.hrtime()`. It probably doesn't matter if you're just doing unit testing, but it might be useful for a game server or something.

**Comment by mikebolt** [comment]
I modified the performance.now polyfill to support node.js. Tween.js now at least can be loaded by node.js without any errors but that's as far as I tested it. Please test my fix (https://github.com/mikebolt/tween.js/tree/node) when you can and post here when you're done. Then I will make a pull request.

**Comment by sole** [comment]
Confirming that performance.now is used because it's more accurate, not because it's more "performant". Thanks for looking into this! I was away the last two weeks =)

**Comment by sole** [comment]
@rosancoderian is this working for you now?

**Comment by rosancoderian** [comment]
haven't test it yet, because it was long ago and i was already using another library back then. i'm closing this issue.

**Comment by juliuszfedyk** [comment]
Still there, trying to use it in a es6 module - and since window is not available in a module - I cannot use it.

Why would you need window for tweens?

**Comment by sole** [comment]
@juliuszfedyk because we are using the `window.performance.now()` as explained in the comment above https://github.com/tweenjs/tween.js/issues/252#issuecomment-230812553

Happy to see a contribution. The library isn't that big and you could add your es6 expertise to it!

**Comment by jshawl** [comment]
In case anyone else is looking - noticed that `window == undefined` is handled correctly in this commit - https://github.com/tweenjs/tween.js/commit/002c1d99f50d99a2c100687079db3e7760222c02

https://github.com/tweenjs/tween.js/blob/ae085330fbc0c4e7911c69e786bd3f697f95943f/src/Tween.js#L74-L99

**Comment by juliuszfedyk** [comment]
Hi @sole - it was my bad. The last version did not pull correctly for some reason. Sorry.

**Comment by sole** [comment]
@juliuszfedyk good to hear! I'll close this again then! Thanks-the contribution offer is still standing, if you find another thing and you can fix it :)
