### ISSUE TITLE
Animating on discrete values (integers instead of floats)

### ISSUE THREAD

**Issue by crecord** [tweenjs/tween.js#253]
This isn't a bug. I just want some advice on how to do something. I am tweening between a couple of arrays of positions. This works great, but I also want to keep track of my index in the array as this is happening to update something independent. 

I am considering keeping track of the time since the tween started and using this to get an approximate of the index or making the index a field in my object. But this seems way to janky! Any suggestions?

```
            xS = [];
            yS = [];
            zS = [];

for(var i=0; i < scaledCurrentlyBeingPlayed.geometry.vertices.length; i+=50 ){
                var thePoint = scaledCurrentlyBeingPlayed.geometry.vertices[i].clone();
                thePoint.applyMatrix4( scaledCurrentlyBeingPlayed.matrixWorld );
                xS.push(thePoint.x); 
                yS.push(thePoint.y); 
                zS.push(thePoint.z); 
            }

var camPathObj = { x: xS[0], y: yS[0], z: zS[0] };
            var tweenCamPath = new TWEEN.Tween( camPathObj ).to( { x: xS, y: yS, z: zS}, 10000 ).onUpdate( function() {
                // how do I find the current index here???
                activeCamera.position.x = this.x;
                activeCamera.position.y = this.y;
                activeCamera.position.z = this.z;
            }).interpolation( TWEEN.Interpolation.CatmullRom ).easing(TWEEN.Easing.Quadratic.InOut );

```

**Comment by mikebolt** [comment]
You could, like you said, calculate the index using the time since the tween started. Once you have the tween's progress value `k`, you can use the same code that the CatmullRom interpolation function uses to get the index `i`:

    var m = v.length - 1;
    var f = m * k;
    var i = Math.floor(f);

I'm not completely sure, but I think that `i` is the index of the value that the tween is currently moving towards.

It may help to simply tween a value `tweenedIndex` linearly from 0 to the last index, then call the function `TWEEN.Interpolation.CatmullRom` yourself inside the onUpdate callback, providing the array (e.g. xS) as the first parameter, and the value `tweenedIndex / numPoints` for the second parameter. You will still need to calculate the index, but you can do that using `math.floor(tweenedIndex)`.

**Comment by trusktr** [comment]
> It may help to simply tween a value tweenedIndex linearly from 0 to the last index

Yep, that seems the easiest way. Just tween a number from 0 to the last index, then use `Math.round()` (or similar) to find the nearest index value.

Maybe a new API can tell tween to animate across discrete values instead of floats?

**Comment by trusktr** [comment]
Looks like none of us have intent or time to make a PR for this, and workarounds exist. Also I'm not sure we should support rare cases like this directly because of the increased library complexity. Closing, but if someone really _really_ needs this, please open a new issue.
