### ISSUE TITLE
NPM answers "No compatible version found: tween@16.3.4"

### ISSUE THREAD

**Issue by damienfa** [tweenjs/tween.js#254]
My version of node is  v5.0.0 and npm v3.3.6
When I try to install tween.js as a dependency of my project (in package.json, I added `"tween": "16.3.4"`in the "dependencies" scope). 
My next `npm install` fails because of this error : 
```
No compatible version found: tween@16.3.4 
Valid install targets: ["0.9.0","0.8.0"] 
```

How do you install it ?

**Comment by mikebolt** [comment]
Make it 'tween.js' instead of 'tween'. 'tween' points to [this package](https://www.npmjs.com/package/tween), which looks like an older version of the project that hasn't been updated in a long time, whereas 'tween.js' points to [this package](https://www.npmjs.com/package/tween.js), which is much more up-to-date.

**Comment by damienfa** [comment]
It works like a charm ! Thanks !
