### ISSUE TITLE
Values not present in the source object should be set in the object

### ISSUE THREAD

**Issue by aliniacob** [tweenjs/tween.js#262]
https://github.com/tweenjs/tween.js/blob/master/src/Tween.js#L158 I think we should be able to set unexisting props in the source object useful when the modified property is a getter or setter.

**Comment by mikebolt** [comment]
This is the opposite of issue #244. The fix for issue #244 resulted in that comment being written ([here's the commit](https://github.com/tweenjs/tween.js/commit/6a6e037e4861683d99f21c87cd394afb2206c17a)).

It would be very easy to change this.

I would like to point out that the current behavior is kind of strange: if the property is strictly undefined, it won't tween at all, but if it's falsy (null, empty string, NaN...) then it will tween starting from 0.0. See [line 207](https://github.com/tweenjs/tween.js/blob/master/src/Tween.js#L307). I will leave it up to someone else to either close this issue or ask for it to be fixed, and at that point another issue should be opened to fix the handling of falsy values to be consistent with the behavior for undefined values.

**Comment by sole** [comment]
The problem with tweening undefined properties is that we do not know the value to tween to (i.e. the destination, final value). Similarly, how do you decide what is the initial value? Which values do you set the source to?

I believe this is something your code should take care of - separation of concerns etc. But I'm happy to hear more from your side. Right now it feels like you want the library to do more things for you when it is a library meant to *interpolate* values, not set them :-)

**Comment by sole** [comment]
@mikebolt yes also the handling of falsy is kinda funny 😏. I believe we put that in place to avoid interpolating between nulls which would result on NaNs. So starting with zero at least didn't introduce instability.

**Comment by aliniacob** [comment]
Ok, I think I was a bit unclear. Let's say we have:

`class ToBeTweened {
  constructor(x) {
    this.position.x = x;
    this.someModifier = someVal;
  }

  get x() {
    return this.position.x * this.someModifier;
  }

  set x(val) {
    this.position.x = val * this.someModifier;
  }
}`

In this case the following wouldn't be possibile:

`let a = new ToBeTweened(0)
 TWEEN.Tween(a)
  .to({x: 100})
`
even tough those are returning and setting real values.

**Comment by dalisoft** [comment]
@aliniacob This can reduce performance and may be make errors when some case as i use and modify tween.js starting at 2013. @sole and other awesome contributors made this app very well and bug-free, even for `IE5.5+ supports` with `Clear Code` with `High-performance`.
Sorry, for bad english. Maybe i'm wrong, fix if i'm wrong.
Thanks.

**Comment by mikebolt** [comment]
I think this is essentially the same as issue #267. At least, if we fixed #267, I think it would support your use case. We don't want to infer starting values, because that could cause some confusing bugs.

Let me know if I am mistaken about your issue.
