### ISSUE TITLE
Removing/stopping+starting tweens inside onComplete callback causes wrong tween deletion

### ISSUE THREAD

**Issue by drnlab** [tweenjs/tween.js#264]
Hi,

First of all, thank you for this awesome lib.

I'm working with tween.js and PIXI in a book-like app with multiple scenes. When changing from one scene to another, this is what happens:
- Start fadeOut...
- When fadeOut is complete:
  - Remove/stop all tweens <--- !?
  - Do some usual stuff like change background, remove/add sprites, stop/play music, etc.
  - Start fadeIn...
- When fadeIn is complete, the new scene is ready.

Not a strange use case, but I'm experiencing what I think is a weird behaviour: after removing or stopping all tweens on fadeOutComplete, fadeIn starts but never updates. I reproduced the issue at: [http://drnlab.net/test/tweenjs/]. Here is the source code:

```
var sprite = { alpha: 0 };

var callbacks = {};

callbacks.onFadeOutUpdate = function() {
    console.log( "onFadeOutUpdate - sprite.alpha = " + sprite.alpha );
};

callbacks.onFadeOutComplete= function() {
    console.log( "onFadeOutComplete.\n\n" );
    //
    TWEEN.removeAll();
    /*
    // Same behaviour stopping all tweens ( please, comment line above - TWEEN.removeAll() - before uncomment this code ):
    var allTweens = TWEEN.getAll();
    for ( var i = allTweens.length - 1; i >= 0 ; i-- ) { // Start from the last index to 0, because tween.stop() changes allTweens.lenght! (?)
        var tween = allTweens[i];
        console.log( "!!! - Stopping 1 tween (fadeOut). Ok!" );
        tween.stop();
    }
    */
    //
    // [...] Do some usual stuff like change background, remove/add sprites, stop/play music, etc.
    //
    console.log( ">>> Start fadeIn!!! - sprite.alpha = " + sprite.alpha );
    tweens.fadeIn.start();
    console.log( "!!! - There is " + TWEEN.getAll().length + " tween to update: our fadeIn. That's ok." );
    console.log( "!!! - And now it suddenly dissapears! :(" );
};

callbacks.onFadeInUpdate = function() {
    console.log( "onFadeInUpdate - sprite.alpha = " + sprite.alpha );
};

callbacks.onFadeInComplete= function() {
    console.log( "onFadeInComplete.\n\n" );
};

var tweens = {};

tweens.fadeOut = new TWEEN.Tween( sprite )
        .to( { alpha: 1 }, 1000 )
        .onUpdate( callbacks.onFadeOutUpdate )
        .onComplete( callbacks.onFadeOutComplete );

tweens.fadeIn = new TWEEN.Tween( sprite )
        .to( { alpha: 0 }, 1000 )
        .onUpdate( callbacks.onFadeInUpdate )
        .onComplete( callbacks.onFadeInComplete );

console.log( ">>> Start fadeOut!!! - sprite.alpha = " + sprite.alpha );
tweens.fadeOut.start();

animate();

function animate() {
    requestAnimationFrame( animate );
    console.log( "Updating " + TWEEN.getAll().length + " tweens." );
    TWEEN.update();
};
```

A zip with this code ready to test:
[tweenjs-issue.zip](https://github.com/tweenjs/tween.js/files/308894/tweenjs-issue.zip)

You can comment/uncomment `TWEEN.removeAll();` to see how the behaviour changes in both cases.

No related issues found in the issue tracker and I've just downloaded the master branch.
Checked with Firefox, Chrome and Edge.

Maybe I'm missing something obvious.

Thanks in advance.

**Comment by mikebolt** [comment]
Hi drnlab. I think I know what's wrong. Here's what's happening:

1. You create the `sprite` object.

2. You create four callbacks.

3. You create the empty `tweens` object.

4. You create and configure two tweens, but do not start them. The important thing to note here is that calling `TWEEN.Tween()` both creates a tween and "adds" it to the internal list of tweens. Until you call `start()`, they just sit there "added" but not "started".

5. You start the `fadeOut` tween.

6. You start your animation loop, which calls `TWEEN.update()` every frame. Because both `fadeOut` and `fadeIn` are added, `TWEEN.update()` will try to update both tweens. For `fadeOut`, it will update the `alpha` value and call the `onFadeOutUpdate` callback. For `fadeIn` it won't do anything because it has not been started yet.

7. Eventually `fadeOut` will finish and call `onFadeOutComplete`, which calls `TWEEN.removeAll()`, which completely empties the internal list of tweens.

8. The next time `TWEEN.update()` is called, it has no tweens in its internal list, so it does nothing.

The solution is to remove the `TWEEN.removeAll()` line, and your code should work exactly like you expect it to. Tweens actually remove themselves after they finish. If you want to reuse a tween after it has finished normally, you would have to first add it using `TWEEN.add`, then start it. You can also just create a new tween.

You never really need to remove tweens, unless you want to stop one before it is finished, in which case you should call `stop()`, which also removes the tween from the internal list. If you have an extremely long or infinite tween, it is a good idea to stop or remove it as soon as possible, because otherwise the interpreter has to hold on to the tween, its callbacks, and whatever values those callbacks might be enclosing, which could be lots of memory.

I hope that was clear. Good luck with your project!

**Comment by drnlab** [comment]
Hi @mikebolt! Thank you very much for your detailed response.

The problem is that calling `new TWEEN.Tween()` doesn't add it to the internal `_tweens` array. The tween is added only when `start()` method is called (which is great for performance because this way the engine iterates/updates over "active" tweens only):
https://github.com/tweenjs/tween.js/blob/master/src/Tween.js#L135

I really need to remove or stop all tweens before they are finished, because users can change from one scene A to scene B while tweens in scene A are still playing. But neither `TWEEN.removeAll()` nor calling `stop()` for each tween in `TWEEN.getAll()` is working for me: `fadeIn.start()` is called but `fadeIn.update()` never fires.

Any ideas? :O

**Comment by mikebolt** [comment]
You're right, it looks like tweens get added when started, not when created.

As far as I can tell your code is correct, and this is a bug in Tween.js. The offending line is [L82](https://github.com/tweenjs/tween.js/blob/master/src/Tween.js#L82), which is responsible for removing a tween after it finishes, but instead it removes your newly created tween.

To work around the issue, start the `fadeIn` tween after the onFadeOutComplete callback finishes. You can do this by setting a flag such as `fadeOutComplete`, then checking for that flag in the update loop.

There are several easy fixes for this bug that may hurt performance if there are tons of tweens. I think a solution that turns the internal tweens list into a kind of iterable hashset would be best. We can give each tween a unique (and entirely internal) ID upon creation, then use that to look up a tween and remove it without hurting performance or relying on splicing with a known index.

**Comment by drnlab** [comment]
Good job Mike! Now I can see where the problem is... and your fix works nice.
I'm going to change the issue description to a more accurate one.
Thank you very much!

**Comment by sole** [comment]
Right, I've merged @mikebolt's fix and run your example with the new version of tween.js and the example actually behaves as @drnlab would like it to behave. I'm going to try turning the example into a test so we can make sure this behaviour is working in the future if changes happen again.

Also I think I could never see this issue because I generally use chain() to schedule tweens to start one after the other... so it was an interesting edge case, thanks for finding :-)

**Comment by sole** [comment]
@drnlab This should be fixed in the current version. Please let us know? Thanks!

**Comment by drnlab** [comment]
Thanks @sole! I'll check it as soon as possible.

**Comment by sole** [comment]
@drnlab did you have a chance to look at this? thanks :)

**Comment by drnlab** [comment]
I've just tested the latest version. It works for me @sole. Sorry for the delay and thanks again!

**Comment by trusktr** [comment]
Tweens are removed from Groups (TWEEN) automatically now, so there's no need to manually remove them when they are finished, and tests are implemented for this. If there is still any issue, please feel free to reply so we can re-open or make a new issue.
