### ISSUE TITLE
Group start

### ISSUE THREAD

**Issue by romanmarkelov** [tweenjs/tween.js#299]
I have 30,000 vertices, whether there is a method that will help run the animation for all vertices in a single thread?

my code:
  `_.times` => it is [lodash method](https://lodash.com/docs/4.17.2#times)
```javascript
function createParticle() {
    let tween;
    _.times(30000, n => {
        let vertex = shirt.geometry.vertices[n];
        let particle = particles.vertices[n];
        particle.x = 15 * 20;
        particle.y = 16 * 20;
        particle.z = 14 * 20;

        tween = new TWEEN.Tween(particle)
            .to({
                x: vertex.x * shirt.scale.x,
                y: vertex.y * shirt.scale.y,
                z: vertex.z * shirt.scale.z
            }, 3000)
            .onUpdate(function() {
                particleSystem.geometry.verticesNeedUpdate = true;
            })
            .easing(TWEEN.Easing.Sinusoidal.InOut)
            .start();
    });
}
```

**Comment by mikebolt** [comment]
Could you explain in more detail what you want to do?

**Comment by mikebolt** [comment]
Are you trying to calculate the tweens in a separate thread? We could support this in the future, but right now all tweens are calculated on the main thread.

I think we could accomplish this by allowing the user to initialize the "global" TWEEN object instead of creating it by default in the main thread.

**Comment by sole** [comment]
Or you could run Tween on a web worker. Nothing is stopping you from doing that (as far as I know)

**Comment by trusktr** [comment]
30000 Tweens on 30000 vertices is a bit much. This doesn't slow down for you @webmarkelov? What sort of computer are you running it on?

> Or you could run Tween on a web worker. Nothing is stopping you from doing that (as far as I know)

We'd still need some interface for getting those values back in a way that end users don't actually need to know how to use Web Workers, otherwise the complexity is too high for people knowing enough JavaScript to get up and running with Tween.js. Keeping it in the back of my mind for later...

**Comment by trusktr** [comment]
I do think we need a `Group` feature, where we can control groups of Tweens at once. It would be similar to TWEEN, but not a global, not containing absolutely every Tween every instantiated.

**Comment by mikebolt** [comment]
We have Tween.Group now and WebWorkers are supported.
