### ISSUE TITLE
Not able to capture onComplete when repeat set to Infinity

### ISSUE THREAD

**Issue by Zergus** [tweenjs/tween.js#303]
I'm trying to create random blinking button with random color. Way I've chose:
```
new AFRAME.TWEEN.Tween(new AFRAME.THREE.Color('#000'))
                .to(toColor, 1000)
                .onUpdate(function () {
                    this_.el.setAttribute('material', { color: `#${this.getHexString()}` });
                })
                .onComplete(function () {
                    Object.assign(toColor, chance.color({format: 'shorthex'}));
                })
                .repeat(Infinity)
                .start();
```

Suspected that animation will get `.onComplete()` callback when each iteration of animation is finished, but this not happened.

Workaround will be to remove `.onComplete()` and create `setInterval(() => Object.assign(toColor, chance.color({format: 'shorthex'})), 1000)` but agree, it looks stupid to create additional cycle to just update color. I don't really think right way is to remove old tween and create new one, or even worse - chain them to infinity.

Is there better way? Thanks, you are awesome!

**Comment by sole** [comment]
`onComplete` is only called on the last iteration, so since you have an infinite repeat, this will never be called, I'm afraid.

We discussed implementing `onBeforeRepeat`: https://github.com/tweenjs/tween.js/issues/290 . You would probably want `onAfterRepeat` or something of that sort. Nothing of this is implemented yet, so your solution is what you can do for now.

**Comment by Zergus** [comment]
Thanks. Used `setInterval`.
