### ISSUE TITLE
Currently 16.4 is released, but it looks like 16.3.5 in npm.

### ISSUE THREAD

**Issue by windofwind** [tweenjs/tween.js#312]
y did not see?

and thx so much! 
i like this lib~

**Comment by mikebolt** [comment]
@sole is on vacation I believe.

**Comment by nordsimon** [comment]
+1 for this, I'm having issues with node and tween which are resolved in this current version

**Comment by sole** [comment]
OK I am having a terrible workload after vacation and haven't had time to look into this yet, you can install from github in the meantime.

**Comment by nordsimon** [comment]
No problem @sole . I did that in the meantime, just wanted to ping you and tell you that there are problems in node that has been resolved. Please reply to me when you have a new version

thanks

**Comment by sole** [comment]
So I have investigated this, it seems that semantic-release is unable to find the differences between versions in order to create a commit log. This is what the [output of the command](https://travis-ci.org/tweenjs/tween.js/builds/194912245) in travis says (make sure to unfold the output of line 486 to read it):

```
[Travis Deploy Once]: Success at attempt 1. All 1 jobs passed.

semantic-release ERR! commits The commit the last release of this package was derived from is not in the direct history of the "master" branch.

semantic-release ERR! commits This means semantic-release can not extract the commits between now and then.

semantic-release ERR! commits This is usually caused by force pushing, releasing from an unrelated branch, or using an already existing package name.

semantic-release ERR! commits You can recover from this error by publishing manually or restoring the commit "b5e62cc88ea2e098f5ca0d2e76e0b74b66985162".

semantic-release ERR! pre Failed to determine new version.

semantic-release ERR! pre ENOTINHISTORY Commit not in history
```

The b5e62cc88ea2e098f5ca0d2e76e0b74b66985162 commit was from the 11 of December... my only guess is that somehow merging using the GitHub UI is confusing the git history (?) but I do not see any discontinuity in the history between that commit and the following commits that should have triggered semantic-release npm publishes:

<img width="934" alt="screen shot 2017-01-24 at 18 30 42" src="https://cloud.githubusercontent.com/assets/5609/22261006/40a1fb12-e263-11e6-917c-f622faa8707d.png">

I have updated `semantic-release` in `package.json` as it was using a very old version, and also hoping that maybe this has been resolved, but it seems the output is the same. All builds after that commit do not result in a successful npm publish.

I'm at a complete loss as to how to fix this, and also how to prevent it in the future as well. Any pointers will be much appreciated. Definitely not really keen on rolling back to that commit and rebuilding history!

PS there's no need to 'ping' or '+1' issues, this only adds extra stress and doesn't help *at all* (cc @nordsimon)

**Comment by finnp** [comment]
@sole I just looked into this. I noticed that the commit from November is b5c08f323f264d66d6af8b9e203b52b8dbce1593 not b5e62cc. They just happen to look alike 😄  

So the problem actually is that at some point someone maybe forced pushed to master. This could be prevented by using a [protected master branch](https://help.github.com/articles/about-protected-branches/) in the future.

To make `semantic-release` work again the easiest solution for this would be to manually publish 16.4.0. Then npm will have a commit hash that is in the history and semantic-release will work again. The alternative would be to use the `16.3.5` tag to rewrite the history on master.

**Comment by sole** [comment]
Ohhh @finnp thank you so much. I was also thinking about doing a manual push before resorting to re-writing commits. Thanks... I'll try this (also look into the settings to avoid force pushes...!)

**Comment by sole** [comment]
🎉 
The trick suggested by @finnp worked! You can see that semantic-release is [happy and finding changes now](https://travis-ci.org/tweenjs/tween.js/builds/195607287).
This is what I did, just in case someone else has the issue in the future:

In my computer, I edited `package.json` and changed the value of`version` manually to `16.4`
Then ran `npm publish`. This published the module to npm.

Now I created a few minor [commits](https://travis-ci.org/tweenjs/tween.js/builds/195602159) updating docs and stuff. Pushed them to GitHub. Travis ran the tests and also semantic-release but since they were `docs:` no release was created. Then I created a commit whose message started with `feat:` and pushed it to GH. This was finally picked by semantic-release and now builds are automatically generated again.

I've also disabled forced pushes to `master`. They should also pass the tests to be merged (this was the idea before, just it was enforced manually by the humans, rather than automatically by the system).
