### ISSUE TITLE
provide context to callback

### ISSUE THREAD

**Issue by uptownhr** [tweenjs/tween.js#359]
Is it possible to provide context to the callback for onUpdate, onComplete? For example,

```
.onUpdate( function(ctx){

})
```
Much clearer then using `this.` and also doesn't conflict with es6 fatarrow.

**Comment by mikebolt** [comment]
For every callback except onUpdate the convention is to pass in the tweened object as the only parameter, and also as the 'this' keyword. For example:

    this._onCompleteCallback.call(this._object, this._object);

However the parameter passed to the onUpdate callback is the tween completion fraction. I would be glad to make a breaking change to fix this so that onUpdate behaves like the other callbacks. I would also like to analyze if it's faster to skip binding 'this'. If it's faster to avoid it, then I will gladly make another breaking change.

**Comment by mikebolt** [comment]
Using a direct function application instead of 'call' is significantly faster in Chrome, IE, and Edge on my computer, using this test: https://jsperf.com/function-calls-direct-vs-apply-vs-call-vs-bind/6. The performance difference between the two was insignificant in Firefox.

**Comment by DVLP** [comment]
creating functions dynamically causes memory allocation so I propose another method to prevent jank
.onUpdate(onUpdateCallback, param1)

function onUpdateCallback(param1) {
}

**Comment by mikebolt** [comment]
I recently changed the code so that there is no binding. The interpolated object is passed in as the only parameter to each callback function. If you have old code that uses 'this' inside of a callback you need to fix it.

If you want to access other values inside your callback, then you can access them through closure.
