### ISSUE TITLE
Infinite recursion loop in readme example causing performance degradation

### ISSUE THREAD

**Issue by Kaptard** [tweenjs/tween.js#385]
### Version
16.6.0

### Steps to reproduce
Run the example code in any arbitrary setInterval loop.

### What is expected?
The recursion should stop once the tween is done, which could be easily done with an `.onComplete` function.

### What is actually happening?
The recursion never stops. In instances where this is used a lot (i.e. multiple real-time update charts) this leads to some very quick performance degradation. 

### Demonstration
https://johnnynotsolucky.github.io/samples/vuejs-d3/
This runs the example code on a data set every 2s, so leave it running for a while (up to 3 minutes) to observe the performance degradation. Looking at the performance tab in firefox, you'll see *a lot* of `requestAnimationFrame` calls being fired as a result.

<br>

**Note**
I'm aware that this may have been left out of the example for the sake of simplicity, but realistically, most people will not look beyond the first examples, and it gets even worse when that code is used in other tutorials, where users will likely not look at the docs at all.

Edit: I made a [PR concerning this issue](https://github.com/tweenjs/tween.js/pull/386).

**Comment by mikebolt** [comment]
It looks like the requestAnimationFrame loops never get destroyed, so each time tweenData is called it will spawn an immortal RAF loop, and each of these loops will call TWEEN.update redundantly. The solution is to move the RAF loop so that you only have one in your application. I'm not yet familiar with Vue.js, but `mounted` in App.vue might be a good place to start the RAF loop.
