### ISSUE TITLE
smoothly end a tween that runs indefinitely  

### ISSUE THREAD

**Issue by tommytee** [tweenjs/tween.js#395]
this is a request unless this feature is already here.

I would like to start a tween that continues indefinitely until told to stop.  When it stops i want it to ease out smoothly and stop.

something like this: http://jsfiddle.net/geekambassador/WccmB/

in that example the tween target is a large number, i would rather it run until stopped, but a large target number would work.

**Comment by mikebolt** [comment]
This is out of the scope of this library.

If you want to do something like this then you can manually add  "speed up" and "slow down" tweens, and try to get the duration correct so that the derivative matches and it feels smooth. Or, you could add some code in your update loop that adds a velocity value to a position value, and changes the velocity value at the right time.
