### ISSUE TITLE
Why return true when current time less than start time?

### ISSUE THREAD

**Issue by trusktr** [tweenjs/tween.js#410]
https://github.com/tweenjs/tween.js/blob/13dec0cafafd42f5e63e240b050c5dc1ee8726cb/src/Tween.js#L336-L338

What's the use case for this?

Would it make more sense to throw an error here?

**Comment by mikebolt** [comment]
Tween.Group's update function calls update on all tweens regardless of whether their start time has passed. This is the only place where the start time is checked. It returns true so that tweens that are added to the group but not playing will stay added to the group until they are ready to be animated.
