### ISSUE TITLE
how can i seek to the specify position?

### ISSUE THREAD

**Issue by weituotian** [tweenjs/tween.js#433]
if i want an animation with 24 frame in 1s.

and i can seek to any frame of the 24 frame, how to make it!

does it imposible? someone have the suggestion?

**Comment by mikebolt** [comment]
If you have a single tween that lasts four seconds and starts at t=1.0 seconds, you can simulate advancing to the `n`th frame of a 24fps animation by updating the tween like this:

    myTween.update(1000 * (1 + n / 24));

or you can use the Group's update method:

    Tween.update(1000 * (1 + n / 24));

With the first method you can safely skip both forward and backward. Note: you might want to add it to a new Tween.Group so that the global update function doesn't mess with your tween. With the second method you should not decrease n on a successive update call, because it will break the library. Mathematically speaking, the update time sequence must be monotonically increasing.
