### ISSUE TITLE
Can't resolve '../.temp.version.js

### ISSUE THREAD

**Issue by alt-romes** [tweenjs/tween.js#546]
When requesting the module I get `Can't resolve '../.temp.version.js` error. I looked at src/Tweet.js:
../temp.version.js is used to set TWEEN.version. After deleting this line the module isn't recognized anymore ( I get an error saying the module @tweenjs/tween.js couldn't be resolved ).
Any help would be appreciated :)

**Comment by trusktr** [comment]
Hi @alt-romes Thanks for reporting this, ad the repo is going through some changes in how it is built, so it will be good to catch these issues before the next release.

Can you explain how you're attempting to consume Tween.js?

**Comment by trusktr** [comment]
If you're trying to import from the file in `src`, for example, that won't work. it has a build step. 

For example, instead of importing https://www.unpkg.com/browse/@tweenjs/tween.js@18.5.0/src/Tween.js you should import one of the dist file at https://www.unpkg.com/browse/@tweenjs/tween.js@18.5.0/dist/ .

If you're using a script tag and need older browser support, you can place a script tag like this:

```html
<script src="https://www.unpkg.com/@tweenjs/tween.js@18.5.0/dist/tween.umd.js"></script>
<script>
  /* ...use the TWEEN global here... */
</script>
```

If you want to use native ES Modules in newer browsers, you can import it like this:

```html
<script type="module">
  import TWEEN from "https://www.unpkg.com/@tweenjs/tween.js@18.5.0/dist/tween.esm.js"

  /* ...use TWEEN here... */
</script>
```

If you are using a build system like Webpack or Rollup, you should be able to just import it like

```js
import TWEEN from '@tweenjs/tween.js'
```

in your code.

Just don't import from `src/` directly, as that needs a build step.

I don't think there is any issue here, but feel free to discuss if needed. We can re-open if there is any issue.
