### ISSUE TITLE
Provide a changelog (esp. v17 -> v18)

### ISSUE THREAD

**Issue by ansf** [tweenjs/tween.js#561]
There seem to be some versions without a changelog.
Specifically I miss what were the breaking changes between v17 and v18.

Thank you for this library! :)

**Comment by trusktr** [comment]
Agreed, that is something we should do. Maybe we can automate it.

**Comment by trusktr** [comment]
By the way, happy to help in case you have some code that doesn't work and I can suggest a workaround/migration.

**Comment by ansf** [comment]
Thanks! I have not upgraded yet.

When looking at https://github.com/tweenjs/tween.js/compare/5ef23f7...a91a535 I don't see any changes that look breaking. So maybe I will just try to upgrade and see if anything breaks.

**Comment by trusktr** [comment]
I think the only major change from 17 to 18 was file name changes. f.e. instead of `src/Tween.js` use `dist/tween.umd.js` for global script tag inclusion of the lib. No need to upgrade if it still works for you really. The only new major thing in 18.6 is TypeScript support, but that's undergoing a fix right now (#568).

**Comment by trusktr** [comment]
We'll aim to make better releases. In the meantime, I'll close this, but feel free to ask any questions. :)
