### ISSUE TITLE
A snippet of Tween.update never runs

### ISSUE THREAD

**Issue by jonobr1** [tweenjs/tween.js#562]
This code ([link](https://github.com/tweenjs/tween.js/blob/master/src/Tween.ts#L331-L334)) never runs because (I think) `isPlaying` is meant to be invoked as a function or accessed via its private reference via underscore.

```typescript
// If the tween was already finished,
if (!this.isPlaying) {
  this.start(time)
}
```

Switching the condition to `if (!this._isPlaying) {` fixes that issue, but breaks the test `Unremoved tweens which have been updated past their finish time may go backward in time`. This is because how `valuesStart` is applied in the `Tween.start` method changes. I would've fixed this myself, but I'm not really sure what your intention is with how `valuesStart` should work, so I figured I'd bring it up for discussion here.

Edit: Perhaps another solution would be to just delete it?

**Comment by trusktr** [comment]
I think that's a typo! `this.isPlaying` will always be truthy, but I don't think that is the intent.

There's a TypeScript config option to prevent that sort of thing actually, maybe we should turn that on.

Most importantly, the intent of the project is in the unit tests. So as long as the existing tests pass (or agreed modified tests pass) then all good to change anything.

**Comment by trusktr** [comment]
Sorry, I misread your question last time, but `valuesStart` is supposed to catch the initial values in the object that the Tween is tweening. This happens in the call to `_setupPrperties` inside the `start` method. It will populate the `_valuesStart` object with the tweened object's initial values.

I suppose we need to write a test for making tweens without having called `start`.

In pre-18.6, calling `update` before calling `start` would result in the animation not working. In 18.6, that check was added which was supposed to start a tween (typos aside), making calling of `start` be optional; however a test was not added for this.

We can either:

- Make calling `update` without first calling `start` throw a helpful error to the console
- Fix it so that it will automatically start the tween if `start` is not called, making `start` optional (but then we need to figure how to handle the `Unremoved tweens which have been updated past their finish time may go backward in time` test case).

**Comment by trusktr** [comment]
This is related: https://github.com/tweenjs/tween.js/pull/271

**Comment by trusktr** [comment]
Fixed in https://github.com/tweenjs/tween.js/pull/573

**Comment by jonobr1** [comment]
Amazing, what I was missing was making the preserve boolean trickle down. Nice work and thank you!

**Comment by trusktr** [comment]
No prob! I renamed the signature to `Tween#update(time, autoStart)` in a newer PR, so it makes more sense in the context of when looking at `Tween#update(time, autoStart)` without taking `Group` into consideration (f.e. tweens with no groups).
