### ISSUE TITLE
Global update() or instance update() don't work with time

### ISSUE THREAD

**Issue by ymongo** [tweenjs/tween.js#586]
From documentation:

>If called without parameters, update will determine the current time in order to find out how long has it been since the last time it ran.
>However you can also pass an explicit time parameter to update. Thus,
>```TWEEN.update(100)```
means "update with time = 100 milliseconds". You can use this to make sure that all the time-dependent functions in your code are using the very same time value. 

I expected that playing with time value, i will have some sort of delay or animation speed decrease in a tween. But nothing is happening 🤔  

[See reproduction on a modified three.js+tween example](https://codesandbox.io/s/keen-glitter-16tfp?runonclick=1): move an object in center of scene and go back smoothly to initial setup.

- With global update() or instance update() without time, when I hit camera home button object gets back smoothly to initial position. 
- When I use global update(time) I get a glitch of one frame and scene freezes, something nothing happens.  With instance update(time) i have an function undefined error. 

To repro; switch boolean lines 56-57 and hit refresh on the preview browser.

**Comment by trusktr** [comment]
> I expected that playing with time value, i will have some sort of delay or animation speed decrease in a tween. But nothing is happening thinking

Hello @ymongo! The tween only updates to where it should be for the time that you passed in. Or to put it another way, the time that you pass in is not a _delta_, it is the _actual time_ at which the tween should be.

So, if you always pass `5000`, then the tween will always be at the same position (the time is staying constant).

To control speed of a tween, you would need to set the `duration` of the tween.

I haven't tried changing that dynamically, not sure what should happen in that case, but I imagine that things should adjust dynamically, and if they don't we should add tests for it.

Here's an update codesandbox, try playing with the same booleans: https://codesandbox.io/s/hungry-mayer-t8jz6?file=/src/index.js

**Comment by ymongo** [comment]
> So, if you always pass 5000, then the tween will always be at the same position (the time is staying constant).

aaaaaaaaah ok got it, thank you! 

Though: 
- Instance update(time) jumps back to origin 🤔 whereas global update(time) works fine
- On instance update( (fakeTime += 2) ) object moves slower than with global update(time), so you can modify tween speed with it

Thanks for your time!

**Comment by trusktr** [comment]
@ymongo 

> On instance update( (fakeTime += 2) ) object moves slower than with global update(time), so you can modify tween speed with it

Yeah, you can choose how fast time progresses if you pass in your own "time" values.

> Instance update(time) jumps back to origin thinking whereas global update(time) works fine

You mean when you press stop? That's because currently `tween.update()` automatically causes the tween to start if it not started. So what is happening is you stopped the tween on click, then the next animation frame calls `tween.update()` which causes the tween to start again (`tween.update()` calls `tween.start()` if the tween is stopped).

In your example, because the `requestAnimationFrame` loops keep going and does not stop, here's the same example but it does not call `tween.update` if the tween is stopped, which works the same as the global-update method:

https://codesandbox.io/s/ecstatic-firefly-mmptp?file=/src/index.js

(note the `if (tween.isPlaying())` which will be false after the stop button is clicked)

**Comment by trusktr** [comment]
I think that should solve the issues. Please feel free to open a new one if you have any other questions or issues. :)
