### ISSUE TITLE
Tween.js not chaining properly

### ISSUE THREAD

**Issue by TheInvoker** [tweenjs/tween.js#626]
I'm trying to use twee.js to chain some animations, however I find it is not working properly.

```
var tween1 = new TWEEN.Tween(car.position)
.to({x: 105}, 1000).onComplete(() => {console.log("done 1 second")}); 
var tween2 = new TWEEN.Tween(car.position)
.to({x: 110}, 1000).onComplete(() => {console.log("done 2 second")}); 
var tween3 = new TWEEN.Tween(car.position)
.to({x: 115}, 1000).onComplete(() => {console.log("done 3 second")}); 

tween1.chain(tween2).chain(tween3).start()

setTimeout(() => {
    console.log(1);
},1000);
setTimeout(() => {
    console.log(2);
}, 2000);
setTimeout(() => {
    console.log(3);
}, 3000);
```

The console prints out

```
1
done 1 second
2
done 3 second
3

```
And after the first second, it speeds up tween2 and tween3. I expect it to print out

```
1
done 1 second
2
done 2 second
3
done 3 second

```
And for each of the 3 tweens to take exactly 1 second. But somehow the library is merging tweens after the first....

http://jsfiddle.net/6gfkenw2/

Does anyone know how to fix this?

**Comment by trusktr** [comment]
Hello! Sorry for the very late reply!


Looks like only one object can be chained at once, not two.

This code,

```js
tween1.chain(tween2).chain(tween3).start()
```

is identical to this code:

```js
tween1.chain(tween2)
tween1.chain(tween3)
tween1.start()
```

The `.chain()` method currently `returns this` (returns the same tween that you called it on).

Basically, `tween2` and `tween3` both got chained to `tween1`, so `tween3` replaced `tween2` as the chained tween of `tween1`.

The code to chain them correctly would be this:

```js
tween1.chain(tween2).start()
tween2.chain(tween3)
```

This demo works like you wanted: http://jsfiddle.net/ajsx1z6q

I wonder if we should modify `.chain()`? Ironically, it is a "chainable" API, but maybe the way it is chainable is not as intuitive. Maybe it should return the chained tween.

In the demo, I wrote

```js
tween1.chain(tween2.chain(tween3)).start()
```

but we could modify `.chain()` (a breaking change) so that the original,


```js
tween1.chain(tween2).chain(tween3).start()
```

would work with each successive tween being return.

Currently, it we want to chain many tweens, it would look like this:


```js
tween1.chain(tween2.chain(tween3.chain(tween4.chain(tween5.chain(tween6))))).start()
```

or

```js
tween1.chain(tween2).start()
tween2.chain(tween3)
tween3.chain(tween4)
tween4.chain(tween5)
tween5.chain(tween6)
```

both of which don't read as nice as

```js
tween1.start().chain(tween2).chain(tween3).chain(tween4).chain(tween5).chain(tween6)
// or
tween1
  .start()
  .chain(tween2)
  .chain(tween3)
  .chain(tween4)
  .chain(tween5)
  .chain(tween6)
```
