### ISSUE TITLE
Is it possible to manage pause/resume status in group?

### ISSUE THREAD

**Issue by DoooReyn** [tweenjs/tween.js#637]
Because of pausing a tween will remove it from the group, and only it could resume itself. 
Therefore, pausing and resuming tweens with group seems to be impossible.

So, it is necessary for me to keep an array of tweens that need to paused when my app entered the background, and then to resume them when my app back to foreground.

Well, I mean to say, `Group.getAll()` should return all added tweens, including the paused ones. And pausing a tween should only remove it from the running queue, rather than its corresponding group.

Best wishes.

**Comment by DoooReyn** [comment]
Through a regrettable oversight, I used a redundant approach to achieve this.
But today I found that I could get this work done by controlling `group.update`.

Sorry about that.

**Comment by trusktr** [comment]
Hey, glad you figured that out! Yep, the `TWEEN` object is just a group, but for larger applications it is much better to create your own groups per component so that you can easily control them separately (for example some part of a UI or graphical experience may have a totally separate animation state than another part, and if either part is finished or no longer needed or animating at differing speed you want to have separate control of them).

**Comment by DoooReyn** [comment]
@trusktr Thanks for your explaination. It is really helpful.
