### ISSUE TITLE
Proposal : Fix runs-on label - Directly specify Ubuntu 22.04

### ISSUE THREAD

**Issue by MasatoMakino** [tweenjs/tween.js#663]
## Overview
Currently, the repository has the runs-on label set as [ubuntu-latest](https://github.com/tweenjs/tween.js/blob/e01bbdbebe2d05509b73bbbe7dc7438228124a9e/.github/workflows/tests.yml#L10), but I propose directly specifying it as ubuntu-22.04 to prepare for future changes. This proposal is based on the update policy of GitHub Actions ([Reference: GitHub Blog](https://github.blog/changelog/2022-11-09-github-actions-ubuntu-latest-workflows-will-use-ubuntu-22-04/)).

## Description
Currently, the runs-on label in the repository is set to ubuntu-latest, which currently corresponds to ubuntu-22.04. However, there is a possibility that the version pointed to by ubuntu-latest will be changed in the future. In such cases, GitHub Actions does not automatically detect the change, and the problem only becomes apparent when the next test is executed.

As a proposal, I suggest directly specifying the runs-on label as ubuntu-22.04 to clearly identify test failures caused by future changes. This will help distinguish whether a test failure is due to a change in the runner image or another modification, reducing confusion in the process.

**Comment by trusktr** [comment]
@MasatoMakino Hello! I have a bunch of repos on ubuntu-latest and haven't had issues. I like to be on latest so I catch issues sooner. Is there some example issue in some repo you can provide as an example?

**Comment by MasatoMakino** [comment]
One pattern where the problem may become apparent is when a package [that requires an apt command to install](https://github.com/Automattic/node-canvas#compiling), such as [node-canvas](https://github.com/Automattic/node-canvas), is tied to the test environment.

If such packages are required, a version update of ubuntu may cause problems with CI.

If you do not plan to install such packages in the future, this change is not necessary. Please close this issue.

**Comment by trusktr** [comment]
Ah yeah, that makes sense. I think that is fine. We don't rely on any Ubuntu packages that are likely to change (f.e. only Node, via `uses: actions/setup-node@v1`, and git with `actions/checkout`).

If such a breakage happens, it would be useful to see the build fail, so that we will become aware of the issue right away. When that happens, then we can either set the Ubuntu version back, or decide how else to move forward.

Plus because we use actions/checkout and actions/setup-node, those projects will fix any such issue upstream anyway.

So I believe the current is totally good.
